// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZJntdkUuPji0ZG1Ua__2SU10EU4_v1w',
    appId: '1:670641814883:web:89a52271e03738246ca756',
    messagingSenderId: '670641814883',
    projectId: 'tatos-blog-project',
    authDomain: 'tatos-blog-project.firebaseapp.com',
    storageBucket: 'tatos-blog-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxcdKfHrTKd4cGFFssrINr-or6KR_DZiM',
    appId: '1:670641814883:android:d1ce11d85b2181f86ca756',
    messagingSenderId: '670641814883',
    projectId: 'tatos-blog-project',
    storageBucket: 'tatos-blog-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxaWl-EwaDCw6m9jfCPazzWAjs_3LbpFQ',
    appId: '1:670641814883:ios:cc0a321784a796b96ca756',
    messagingSenderId: '670641814883',
    projectId: 'tatos-blog-project',
    storageBucket: 'tatos-blog-project.appspot.com',
    iosClientId: '670641814883-mlt6ucvla8kfqa9uicb0jv0k1p4mhqn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxaWl-EwaDCw6m9jfCPazzWAjs_3LbpFQ',
    appId: '1:670641814883:ios:cc0a321784a796b96ca756',
    messagingSenderId: '670641814883',
    projectId: 'tatos-blog-project',
    storageBucket: 'tatos-blog-project.appspot.com',
    iosClientId: '670641814883-mlt6ucvla8kfqa9uicb0jv0k1p4mhqn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
